name: Sync Fork with Upstream (PR)

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - 'yardenofir/autoUpstreamSync'  # TODO: Remove (Trigger when there's a push to this branch)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures all history is fetched

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/airbytehq/airbyte.git || echo "Upstream remote already exists"
          git fetch upstream --prune

      - name: Create Sync Branch
        run: |
          git config --global user.email "gh-svc@pulse-security.io"
          git config --global user.name "Auto Syncer"
          git checkout -b sync-upstream-$(date +'%d-%m-%Y_%H-%M')
          git merge upstream/master --no-edit
          echo "BRANCH_NAME=syncUpstream/$(date +'%d-%m-%Y_%H-%M')" >> $GITHUB_ENV

      - name: Push Sync Branch
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          base: master
          title: "Sync Upstream Changes - $(date +'%d-%m-%Y')"
          body: |
            This PR syncs the latest changes from the upstream repository into `master`.
            
            **Branch:** `{{ env.BRANCH_NAME }}`
          labels: |
            automated
            upstream-sync